pipeline {
    parameter{
        choice(name: 'terraformAction', choices: ['apply','destroy'], description: 'choose terraform action to perform')
    }

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    agent any
    stages{
        stage('checkout'){
            steps {
                script{
                    dir ("terrform")
                    git branch: 'feature' url:""
                }
            }
        }
    }
}