pipeline {
    agent any

    parameters {
        choice(
            name: 'terraformAction',
            choices: ['apply', 'destroy'],
            description: 'Choose Terraform action'
        )
    }

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION    = 'us-east-1'
    }

    tools {
        git 'Default'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/feature']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/Gangappa98/test-1.git'
                    ]]
                ])
            }
        }

        stage('Terraform Init') {
            steps {
                dir('project-1') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('project-1') {
                    sh 'terraform plan -out=tfplan'
                    sh 'terraform show -no-color tfplan > tfplan.txt'
                }
            }
        }

        stage('Approval') {
            steps {
                script {
                    def plan = readFile 'project-1/tfplan.txt'
                    input message: 'Do you want to proceed?',
                          parameters: [
                              text(
                                  name: 'Terraform Plan',
                                  description: 'Review the Terraform plan',
                                  defaultValue: plan
                              )
                          ]
                }
            }
        }

        stage('Apply or Destroy') {
            steps {
                dir('project-1') {
                    script {
                        if (params.terraformAction == 'apply') {
                            sh 'terraform apply -input=false tfplan'
                        } else {
                            sh 'terraform destroy -auto-approve'
                        }
                    }
                }
            }
        }
    }
}
